### PR TITLE
Feature/front end/edit button

### PR DESCRIPTION
**Pull request by HeIp**
#FF0000 **DO NOT MERGE** - To Everyone |  Designated For Sprint 2

Features/Bugs/Improvement:

1. Fixed Edit Button Functionality - Now Responsive & Takes you to edit page instead of course page | Addresses #23 
2) Sign out Button - Functionality is still pending | Assistance would be nice

### CODE REVIEW

**Comment by HeIp** [comment]
At this point this Branch takes care of user story point #7 intended for Sprint 2 @ #27

**Comment by HeIp** [comment]
Hopefully by tomorrow we'll have a  Netlify deployment pipeline with travis to deploy incremental  to address #28

**Comment by HeIp** [comment]
Front Deployment Pipeline working !!!!!!!!!

**Review by jessica — APPROVED** [review]

**Review by cbarb — APPROVED** [review]

**Review by HeIp — COMMENTED** [review]
#45

**Review by HeIp — COMMENTED** [review]
#45 test

**Review by verociraptor — APPROVED** [review]

**Comment by HeIp** [comment]
React Linting Warnings have all been addressed at this point in time

**Review by Eberm024 — APPROVED** [review]

**Pull request merged**
