### PR TITLE
Feature/implement quiz question progress

### PR DESCRIPTION
**Pull request by Eberm024**

### CODE REVIEW

**Review by Eberm024 — COMMENTED** [review]
I highly recommend checking the GraphQLSchema.ts mainly because these changes were done in one of my branches and not into dev directly (this is commit 471129b). Also there were changes to frontend mutations and some backend mutations.

**Review by deellah — APPROVED** [review]

**Comment by alemasserrano** [comment]
To resolve conflicts:
`git merge dev` from `feature/implement-quiz-question-progress`
resolve conflicts from branch
push changes

**Review by alemasserrano — COMMENTED** [review]
For the files that you created, can you remove the commented lines and the console logs?

**Review by verociraptor — APPROVED** [review]

**Review by lloyd4546 — APPROVED** [review]

**Review by alemasserrano — APPROVED** [review]
looks good to me

**Pull request merged**
